[tool.poetry]
name = "promptjson"
version = "0.1.0"
description = ""
authors = ["Jered Sutton"]
license = "Apache 2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jsonschema = "^4.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
